"""Authoritative evaluator directory imported from 203 Evaluators Roles.xlsx."""

BASE_EVALUATORS: tuple[tuple[str, str], ...] = (
    ("Wahle", "overall"),
    ("Tawshée", "overall"),
    ("Jalta", "overall"),
    ("Antar", "overall"),
    ("Alex", "overall"),
    ("Che3le", "overall"),
    ("Gem", "overall"),
    ("Maroun", "overall"),
    ("Ghassan", "overall"),
    ("Jane", "overall"),
    ("Theo", "overall"),
    ("Azelie", "overall"),
    ("Odicho", "dossard"),
    ("Wess", "overall"),
    ("Badro", "overall"),
    ("Rotana", "overall"),
    ("Kebous", "overall"),
    ("Retouche", "overall"),
    ("Mendo", "overall"),
    ("Chafic", "overall"),
    ("Paste", "overall"),
    ("Donald", "overall"),
    ("Katy", "overall"),
    ("Coma", "overall"),
    ("Andy", "dossard"),
    ("Maria Khoury", "dossard"),
    ("Marita", "dossard"),
    ("Harbieh", "overall"),
    ("Fuse", "overall"),
    ("Bronzo", "overall"),
    ("Vicky", "overall"),
    ("Sasa", "overall"),
    ("Karl Azar", "overall"),
    ("Alexia", "overall"),
    ("Elie", "overall"),
    ("Mathilde", "overall"),
    ("Chloe", "overall"),
    ("Presto", "overall"),
    ("Clara Abi Chebel", "dossard"),
    ("Wazo", "dossard"),
    ("Zeina", "dossard"),
    ("Samir", "overall"),
    ("Derbess", "overall"),
    ("El Asle", "overall"),
    ("Pipa", "overall"),
    ("Darwin", "overall"),
    ("Tala", "overall"),
    ("MT", "overall"),
    ("Jerry", "overall"),
    ("Clara Hanna", "overall"),
    ("Christian", "overall"),
    ("Jean", "overall"),
    ("Ala2", "overall"),
    ("JP Chaaya", "dossard"),
    ("Diala", "dossard"),
    ("Tina", "dossard"),
    ("Antelias", "overall"),
    ("Amir", "overall"),
    ("Geryo", "overall"),
    ("Goofy", "overall"),
    ("Velma", "overall"),
    ("Alya", "overall"),
    ("Zakka", "overall"),
    ("JD", "overall"),
    ("Celine", "overall"),
    ("Tia", "overall"),
    ("Bieber", "overall"),
    ("Jayjay", "dossard"),
    ("Lea Sadaka", "dossard"),
    ("Pia", "dossard"),
    ("Dingus", "overall"),
    ("Mika", "overall"),
    ("Moudir", "overall"),
    ("Choufani", "overall"),
    ("Diva", "overall"),
    ("Youssi", "overall"),
    ("Cheyene", "overall"),
    ("Mira", "overall"),
    ("Mary", "overall"),
    ("Cynthia", "overall"),
    ("Youhanna", "dossard"),
    ("Lea Dona", "dossard"),
)
